# Cory Booker, Tulsi Gabbard, Pete Buttigieg, Elizabeth Warren, Joe Biden, Bernie Sanders, Amy Klobuchar, Andrew Yang,  Tom Steyer


cd \Users\sarah\Dropbox\Insight_fellowship\Project\Directory\data\raw\Debates\Tweets_Debate_20191121



#Klobuchar
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Klobuchar_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Klobuchar_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Klobuchar OR Amy OR #Klobuchar) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Klobuchar_tweets.json -l 10000

#Harris
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Harris_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Harris_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Harris OR Kamala OR #Harris) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Harris_tweets.json -l 10000


#Booker
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Booker_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Booker_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Booker OR Cory OR #Booker) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Booker_tweets.json -l 10000

#Gabbard
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Gabbard_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Gabbard_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Gabbard OR Cory OR #Gabbard) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Gabbard_tweets.json -l 10000


#Biden
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Biden_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Biden_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Biden OR Joe OR #Biden) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Biden_tweets.json -l 10000


#Buttigieg
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Buttigieg_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Buttigieg_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Buttigieg OR Pete OR #Buttigieg) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Buttigieg_tweets.json -l 10000


#Warren
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Warren_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Warren_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Warren OR Elizabeth OR #Warren) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Warren_tweets.json -l 10000


#Sanders
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Sanders_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Sanders_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Sanders OR Bernie OR #Sanders) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Sanders_tweets.json -l 10000


#Yang
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Yang_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Yang_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Yang OR Andrew OR #Yang) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Yang_tweets.json -l 10000


#Steyer
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (#Denver OR Denver OR Colorado OR #Colorado)" -bd 2019-11-21 -ed 2019-11-29 -o Col_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (Jacksonville OR Tampa OR Miami OR #Jacksonville OR #Tampa OR #Miami OR Florida OR #Florida)" -bd 2019-11-21 -ed 2019-11-29 -o Flo_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (#DesMoines ORDesMoines OR #Iowa OR Iowa)" -bd 2019-11-21 -ed 2019-11-29 -o Iow_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (Flint OR #Flint OR Detroit OR Michigan OR #Detroit OR #Michigan)" -bd 2019-11-21 -ed 2019-11-29 -o Mic_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND ( #TwinCities OR TwinCities OR Minneaopolis OR Minnesota OR #Minnesota)" -bd 2019-11-21 -ed 2019-11-29 -o Min_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (Vegas OR Reno OR #Vegas OR #Reno OR Nevada OR #Nevada)" -bd 2019-11-21 -ed 2019-11-29 -o Nev_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (Manchester OR #Manchester OR New Hampshire OR #NewHampshire)" -bd 2019-11-21 -ed 2019-11-29 -o New_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (Charlotte OR Raleigh OR Greensboro OR #Charlotte OR #Raleigh OR #Greensboro OR North Carolina OR #NorthCarolina)" -bd 2019-11-21 -ed 2019-11-29 -o Nor_20191121_Steyer_tweets_2K.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND (Columbus OR Cleveland OR Cincinnati OR Ohio OR #Columbus OR #Cleveland OR #Cincinnati OR #Ohio)" -bd 2019-11-21 -ed 2019-11-29 -o Ohi_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND ( Philadelphia OR Pittsburg OR Pennsylvania OR #Philadelphia OR #Pittsburg OR #Pennsylvania)" -bd 2019-11-21 -ed 2019-11-29 -o Pen_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND ( Richmond OR Virginia OR #Richmond OR #Virginia)" -bd 2019-11-21 -ed 2019-11-29 -o Vir_20191121_Steyer_tweets.json -l 10000
twitterscraper "(#democraticdebate OR #demdebate OR #debates2019 OR debate OR debates OR primary OR primaries OR election OR vote OR #debate OR #debates) AND (Steyer OR Tom OR #Steyer) AND ( Madison OR Miluakee OR Green Bay OR Wisconsin OR #Madison OR #Miluakee OR #GreenBay OR #Wisconsin)" -bd 2019-11-21 -ed 2019-11-29 -o Wis_20191121_Steyer_tweets.json -l 10000
